EntryExamsApp/Models/Enrollee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EntryExamsApp.Models
{
    public class Enrollee : Person
    {
        [Required]
        [Display(Name = "Адрес")]
        public string Address { get; set; }

        [Display(Name = "Год рождения")]
        [Range(1, int.MaxValue)]
        public int BirthYear { get; set; }

        [Required]
        [Display(Name = "Паспорт")]
        public string Passport { get; set; }

        public List<Exam> Exams { get; set; }
    }
}

EntryExamsApp/Models/Exam.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EntryExamsApp.Models
{
    public class Exam
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Оценка")]
        [Range(1, 5)]
        public int Mark { get; set; }

        [Required]
        [Display(Name = "Дата сдачи")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        [Display(Name = "Абитуриент")]
        public Enrollee Enrollee { get; set; }

        [Display(Name = "Абитуриент")]
        public int EnrolleeId { get; set; }

        [Display(Name = "Экзаменатор")]
        public Examiner Examiner { get; set; }

        [Display(Name = "Экзаменатор")]
        public int ExaminerId { get; set; }

        [Display(Name = "Дисциплина")]
        public Discipline Discipline { get; set; }

        [Display(Name = "Дисциплина")]
        public int DisciplineId { get; set; }
    }
}

EntryExamsApp/Models/Examiner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EntryExamsApp.Models
{
    public class Examiner : Person
    {
        [Display(Name = "Цена приема")]
        [Range(1, int.MaxValue)]
        public int ExamPrice { get; set; }

        public List<Exam> Exams { get; set; }
    }
}

EntryExamsApp/Models/ViewModels/EnrolleeViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EntryExamsApp.Models.ViewModels
{
    public class EnrolleeViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Фамилия")]
        public string Surname { get; set; }

        [Required]
        [Display(Name = "Имя")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Отчество")]
        public string Patronymic { get; set; }

        [Display(Name = "Фото")]
        public IFormFile Photo { get; set; }

        public string PhotoPath { get; set; }

        [Required]
        [Display(Name = "Адрес")]
        public string Address { get; set; }

        [Display(Name = "Год рождения")]
        [Range(1, int.MaxValue)]
        public int BirthYear { get; set; }

        [Required]
        [Display(Name = "Паспорт")]
        public string Passport { get; set; }
    }
}

EntryExamsApp/Models/ViewModels/ExaminerViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EntryExamsApp.Models.ViewModels
{
    public class ExaminerViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Фамилия")]
        public string Surname { get; set; }

        [Required]
        [Display(Name = "Имя")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Отчество")]
        public string Patronymic { get; set; }

        [Display(Name = "Фото")]
        public IFormFile Photo { get; set; }

        public string PhotoPath { get; set; }

        [Display(Name = "Цена приема")]
        [Range(1, int.MaxValue)]
        public int ExamPrice { get; set; }
    }
}

EntryExamsApp/Controllers/EnrolleesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EntryExamsApp.Models;
using EntryExamsApp.Models.Data;
using EntryExamsApp.Models.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace EntryExamsApp.Controllers
{
    public class EnrolleesController : Controller
    {
        private readonly EntryExamsDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EnrolleesController(EntryExamsDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
        }

        // GET: Enrollees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Enrollees.ToListAsync());
        }

        // GET: Enrollees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollee = await _context.Enrollees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (enrollee == null)
            {
                return NotFound();
            }

            return View(enrollee);
        }

        // GET: Enrollees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Enrollees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EnrolleeViewModel enrolleeViewModel)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(enrolleeViewModel);

                Enrollee enrollee = new Enrollee
                {
                    Surname = enrolleeViewModel.Surname,
                    Name = enrolleeViewModel.Name,
                    Patronymic = enrolleeViewModel.Patronymic,
                    Address = enrolleeViewModel.Address,
                    BirthYear = enrolleeViewModel.BirthYear,
                    Passport = enrolleeViewModel.Passport,
                    Photo = uniqueFileName
                };

                _context.Add(enrollee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(enrolleeViewModel);
        }

        // загрузка файла и сохранение его с уникальным именем
        private string UploadedFile(EnrolleeViewModel model)
        {
            string uniqueFileName = null;

            if (model.Photo != null)
            {
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(webHostEnvironment.WebRootPath, "img", "persons", uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        // GET: Enrollees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollee = await _context.Enrollees.FindAsync(id);
            if (enrollee == null)
            {
                return NotFound();
            }

            EnrolleeViewModel viewModel = new EnrolleeViewModel
            {
                Id = enrollee.Id,
                Surname = enrollee.Surname,
                Name = enrollee.Name,
                Patronymic = enrollee.Patronymic,
                Address = enrollee.Address,
                BirthYear = enrollee.BirthYear,
                Passport = enrollee.Passport,
                PhotoPath = enrollee.Photo
            };
            return View(viewModel);
        }

        // POST: Enrollees/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Address,BirthYear,Passport,Id,Surname,Name,Patronymic,Photo,PhotoPath")] EnrolleeViewModel enrolleeViewModel)
        {
            if (id != enrolleeViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                Enrollee enrollee = new Enrollee
                {
                    Id = enrolleeViewModel.Id,
                    Surname = enrolleeViewModel.Surname,
                    Name = enrolleeViewModel.Name,
                    Patronymic = enrolleeViewModel.Patronymic,
                    Address = enrolleeViewModel.Address,
                    BirthYear = enrolleeViewModel.BirthYear,
                    Passport = enrolleeViewModel.Passport,
                    Photo = enrolleeViewModel.PhotoPath
                };

                if (enrolleeViewModel.Photo != null)
                {
                    var fileName = UploadedFile(enrolleeViewModel);
                    enrollee.Photo = fileName;
                }

                _context.Update(enrollee);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(enrolleeViewModel);
        }

        // GET: Enrollees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollee = await _context.Enrollees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (enrollee == null)
            {
                return NotFound();
            }

            return View(enrollee);
        }

        // POST: Enrollees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enrollee = await _context.Enrollees.FindAsync(id);
            _context.Enrollees.Remove(enrollee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnrolleeExists(int id)
        {
            return _context.Enrollees.Any(e => e.Id == id);
        }
    }
}

EntryExamsApp/Controllers/ExaminersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EntryExamsApp.Models;
using EntryExamsApp.Models.Data;
using EntryExamsApp.Models.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace EntryExamsApp.Controllers
{
    public class ExaminersController : Controller
    {
        private readonly EntryExamsDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public ExaminersController(EntryExamsDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
        }

        // GET: Examiners
        public async Task<IActionResult> Index()
        {
            return View(await _context.Examiners.ToListAsync());
        }

        // GET: Examiners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var examiner = await _context.Examiners
                .FirstOrDefaultAsync(m => m.Id == id);
            if (examiner == null)
            {
                return NotFound();
            }

            return View(examiner);
        }

        // GET: Examiners/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Examiners/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExamPrice,Id,Surname,Name,Patronymic,Photo")] ExaminerViewModel examinerViewModel)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(examinerViewModel);
                Examiner examiner = new Examiner
                {
                    Surname = examinerViewModel.Surname,
                    Name = examinerViewModel.Name,
                    Patronymic = examinerViewModel.Patronymic,
                    Photo = uniqueFileName,
                    ExamPrice = examinerViewModel.ExamPrice
                };

                _context.Add(examiner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(examinerViewModel);
        }

        // загрузка файла и сохранение его с уникальным именем
        private string UploadedFile(ExaminerViewModel model)
        {
            string uniqueFileName = null;

            if (model.Photo != null)
            {
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(webHostEnvironment.WebRootPath, "img", "persons", uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        // GET: Examiners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var examiner = await _context.Examiners.FindAsync(id);
            if (examiner == null)
            {
                return NotFound();
            }

            ExaminerViewModel viewModel = new ExaminerViewModel
            {
                Id = examiner.Id,
                Surname = examiner.Surname,
                Name = examiner.Name,
                Patronymic = examiner.Patronymic,
                ExamPrice = examiner.ExamPrice,
                PhotoPath = examiner.Photo
            };
            return View(viewModel);
        }

        // POST: Examiners/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExamPrice,Id,Surname,Name,Patronymic,Photo,PhotoPath")] ExaminerViewModel examinerViewModel)
        {
            if (id != examinerViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Examiner examiner = new Examiner
                {
                    Id = examinerViewModel.Id,
                    Surname = examinerViewModel.Surname,
                    Name = examinerViewModel.Name,
                    Patronymic = examinerViewModel.Patronymic,
                    ExamPrice = examinerViewModel.ExamPrice,
                    Photo = examinerViewModel.PhotoPath
                };

                if (examinerViewModel.Photo != null)
                {
                    var fileName = UploadedFile(examinerViewModel);
                    examiner.Photo = fileName;
                }

                _context.Update(examiner);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(examinerViewModel);
        }

        // GET: Examiners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var examiner = await _context.Examiners
                .FirstOrDefaultAsync(m => m.Id == id);
            if (examiner == null)
            {
                return NotFound();
            }

            return View(examiner);
        }

        // POST: Examiners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var examiner = await _context.Examiners.FindAsync(id);
            _context.Examiners.Remove(examiner);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExaminerExists(int id)
        {
            return _context.Examiners.Any(e => e.Id == id);
        }
    }
}

EntryExamsApp/Views/Shared/_EnrolleesTable.cshtml
@model IEnumerable<EntryExamsApp.Models.Enrollee>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th class="fit">
                @Html.DisplayNameFor(model => model.Photo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patronymic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Passport)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthYear)
            </th>
            <th class="text-center fir"><i class="fas fa-cogs"></i></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="fit">
                    <img src="~/img/persons/@Html.DisplayFor(modelItem => item.Photo)" alt="photo" width="60" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Patronymic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Passport)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BirthYear)
                </td>
                <td class="p-0 fit">
                    <a class="d-block text-center" asp-controller="Enrollees" asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info-circle m-1"></i></a>
                    <a class="d-block text-center" asp-controller="Enrollees" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit m-1"></i></a>
                    <a class="d-block text-center" asp-controller="Enrollees" asp-action="Delete" asp-route-id="@item.Id"><i class="fas text-danger m-1 fa-trash"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

EntryExamsApp/Views/Shared/_ExaminersTable.cshtml
@model IEnumerable<EntryExamsApp.Models.Examiner>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th class="fit">
                @Html.DisplayNameFor(model => model.Photo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patronymic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExamPrice)
            </th>
            <th class="fit text-center"><i class="fas fa-cogs"></i></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="fit">
                    <img src="~/img/persons/@Html.DisplayFor(modelItem => item.Photo)" alt="photo" width="60" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Patronymic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExamPrice) руб.
                </td>
                <td class="p-0 fit">
                    <a class="d-block text-center" asp-controller="Examiners" asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info-circle m-1"></i></a>
                    <a class="d-block text-center" asp-controller="Examiners" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit m-1"></i></a>
                    <a class="d-block text-center" asp-controller="Examiners" asp-action="Delete" asp-route-id="@item.Id"><i class="fas text-danger m-1 fa-trash"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

EntryExamsApp/Views/Shared/_ExamsTable.cshtml
@model IEnumerable<EntryExamsApp.Models.Exam>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Enrollee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Examiner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Discipline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mark)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Enrollee.Surname)
                    @Html.DisplayFor(modelItem => item.Enrollee.Name)
                    @Html.DisplayFor(modelItem => item.Enrollee.Patronymic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Examiner.Surname)
                    @Html.DisplayFor(modelItem => item.Examiner.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Discipline.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mark)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td class="p-0 fit">
                    <a class="d-block text-center" asp-controller="Exams" asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info-circle m-1"></i></a>
                    <a class="d-block text-center" asp-controller="Exams" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit m-1"></i></a>
                    <a class="d-block text-center" asp-controller="Exams" asp-action="Delete" asp-route-id="@item.Id"><i class="fas text-danger m-1 fa-trash"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

EntryExamsApp/Views/Shared/_Layout.cshtml
@using EntryExamsApp.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <!-- header -->
    <header class="navbar navbar-expand-sm bg-primary navbar-dark">
        <!-- Иконка -->
        <a class="navbar-brand" href="#">
            <img src="~/img/kb_logo.svg" alt="KB logo" />
        </a>

        <!--Кнопка для разворачивания меню-->
        <button aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                data-target="#navbarToggler" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Навигация -->
        <div class="collapse navbar-collapse" id="navbarToggler">
            <ul class="navbar-nav">
                @* https://stackoverflow.com/a/20411015/12637295 *@
                <li class="nav-item px-3 @Html.IsSelected(null, "Home")">
                    <a asp-controller="Home" asp-action="Index" class="nav-link">
                        <i class="fas fa-home pr-1"></i>
                        <span>Главная страница</span>
                    </a>
                </li>
                <li class="nav-item px-3 @Html.IsSelected("Create,Delete,Details,Edit,Index", "Enrollees")">
                    <a asp-controller="Enrollees" asp-action="Index" class="nav-link">
                        <i class="fas fa-user-graduate pr-1"></i>
                        <span>Абитуриенты</span>
                    </a>
                </li>
                <li class="nav-item px-3 @Html.IsSelected("Create,Delete,Details,Edit,Index", "Examiners")">
                    <a asp-controller="Examiners" asp-action="Index" class="nav-link">
                        <i class="fas fa-chalkboard-teacher pr-1"></i>
                        <span>Экзаменаторы</span>
                    </a>
                </li>
                <li class="nav-item px-3 @Html.IsSelected("Create,Delete,Details,Edit,Index", "Exams")">
                    <a asp-controller="Exams" asp-action="Index" class="nav-link">
                        <i class="fas fa-icons pr-1"></i>
                        <span>Экзамены</span>
                    </a>
                </li>
                <li class="nav-item px-3 @Html.IsSelected(null, "Queries")">
                    <a asp-controller="Queries" asp-action="Query1" class="nav-link">
                        <i class="fas fa-pen-alt pr-1"></i>
                        <span>Запросы</span>
                    </a>
                </li>
            </ul>
        </div>
    </header>

    @RenderBody()


    <!-- footer -->
    <footer class="footer container-fluid bg-primary text-light">
        <span>Богдан, ПД811, Донецк, 2020</span>
        <a href="mailto:klm_b@outlook.com">
            <i class="fas fa-envelope pl-2 text-success"></i>
        </a>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("scripts", required: false)
</body>
</html>